[server]
headless = true
enableCORS = false

[theme]
base = "dark"
primaryColor = "#8A2BE2"  # Vibrant purple
backgroundColor = "#0E1117"  # Dark blue-gray
secondaryBackgroundColor = "#192841"  # Deeper blue
textColor = "#F0F2F6"
font = "sans serif"